In [1]:
import pandas as pd
df=pd.read_csv(r"C:\Users\polpi\Desktop\data science\assignments\Recommendation System\anime.csv")
df

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [2]:
df.isnull().sum()

anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

In [3]:
df['genre'].unique()

array(['Drama, Romance, School, Supernatural',
       'Action, Adventure, Drama, Fantasy, Magic, Military, Shounen',
       'Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen',
       ..., 'Hentai, Sports', 'Drama, Romance, School, Yuri',
       'Hentai, Slice of Life'], dtype=object)

In [4]:
df_norate=df.drop('rating',axis=1)
df_cleaned=df.dropna()
df_cleaned.isnull().sum()

anime_id    0
name        0
genre       0
type        0
episodes    0
rating      0
members     0
dtype: int64

In [5]:
df_cleaned.columns

Index(['anime_id', 'name', 'genre', 'type', 'episodes', 'rating', 'members'], dtype='object')

In [6]:
cat_col_names = df_cleaned.select_dtypes(include=['object', 'category']).columns.tolist()
print(cat_col_names)

['name', 'genre', 'type', 'episodes']

In [7]:
non_numeric_rows = df_cleaned[~df_cleaned['episodes'].apply(lambda x: str(x).isdigit())]
non_numeric_rows

,anime_id,name,genre,type,episodes,rating,members
74,21,One Piece,"Action, Adventure, Comedy, Drama, Fantasy, Sho...",TV,Unknown,8.58,504862
252,235,Detective Conan,"Adventure, Comedy, Mystery, Police, Shounen",TV,Unknown,8.25,114702
615,1735,Naruto: Shippuuden,"Action, Comedy, Martial Arts, Shounen, Super P...",TV,Unknown,7.94,533578
991,966,Crayon Shin-chan,"Comedy, Ecchi, Kids, School, Shounen, Slice of...",TV,Unknown,7.73,26267
1021,33157,Tanaka-kun wa Itsumo Kedaruge Specials,"Comedy, School, Slice of Life",Special,Unknown,7.72,5400
...,...,...,...,...,...,...,...
11648,32238,"Watashi wa, Kairaku Izonshou",Hentai,OVA,Unknown,6.32,1569
11752,28169,Buta no Gotoki Sanzoku ni Torawarete Shojo wo ...,Hentai,OVA,Unknown,6.14,1992
12024,30770,Maid-san to Boin Damashii,"Harem, Hentai",OVA,Unknown,5.71,1498
12045,33125,Shiiku x Kanojo: Tenshi no Kousoku-hen,Hentai,OVA,Unknown,5.68,1326
12251,33960,Chou Do M na Hentai Mesu-tachi Otokoton Chouky...,Hentai,OVA,Unknown,8.38,161

In [8]:
unique_strings = df_cleaned[df_cleaned['episodes'].apply(lambda x: isinstance(x, str))]['episodes'].unique()

print(unique_strings)

['1' '64' '51' '24' '10' '148' '110' '13' '201' '25' '22' '75' '4' '26'
 '12' '27' '43' '74' '37' '2' '11' '99' 'Unknown' '39' '101' '47' '50'
 '62' '33' '112' '23' '3' '94' '6' '8' '14' '7' '40' '15' '203' '77' '291'
 '120' '102' '96' '38' '79' '175' '103' '70' '153' '45' '5' '21' '63' '52'
 '28' '145' '36' '69' '60' '178' '114' '35' '61' '34' '109' '20' '9' '49'
 '366' '97' '48' '78' '358' '155' '104' '113' '54' '167' '161' '42' '142'
 '31' '373' '220' '46' '195' '17' '1787' '73' '147' '127' '16' '19' '98'
 '150' '76' '53' '124' '29' '115' '224' '44' '58' '93' '154' '92' '67'
 '172' '86' '30' '276' '59' '72' '330' '41' '105' '128' '137' '56' '55'
 '65' '243' '193' '18' '191' '180' '91' '192' '66' '182' '32' '164' '100'
 '296' '694' '95' '68' '117' '151' '130' '87' '170' '119' '84' '108' '156'
 '140' '331' '305' '300' '510' '200' '88' '1471' '526' '143' '726' '136'
 '1818' '237' '1428' '365' '163' '283' '71' '260' '199' '225' '312' '240'
 '1306' '1565' '773' '1274' '90' '475' '263' '83' '85' '1006' '80' '162'
 '132' '141' '125']

In [9]:
df_cleaned=df_cleaned[df_cleaned['episodes'] !='Unknown']
df_cleaned

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [10]:
df_cleaned['episodes'] = pd.to_numeric(df_cleaned['episodes'], errors='coerce')
print(df_cleaned['episodes'].isna().sum())

0

In [11]:
df_cleaned.describe()

           anime_id      episodes        rating       members
count  11830.000000  11830.000000  11830.000000  1.183000e+04
mean   13404.150211     12.486729      6.484609  1.851100e+04
std    11110.087616     47.097131      1.019147  5.537144e+04
min        1.000000      1.000000      1.670000  1.200000e+01
25%     3326.250000      1.000000      5.892500  2.322500e+02
50%     9820.500000      2.000000      6.570000  1.589500e+03
75%    23302.500000     12.000000      7.190000  9.832000e+03
max    34519.000000   1818.000000     10.000000  1.013917e+06

In [12]:
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()

In [13]:
df_clean=df_cleaned.drop(['name'],axis=1)
df_clean['genre']=lab.fit_transform(df_clean['genre'])
df_clean['type']=lab.fit_transform(df_clean['type'])
df_clean

       anime_id  genre  type  episodes  rating  members
0         32281   2651     0         1    9.37   200630
1          5114    159     5        64    9.26   793665
2         28977    526     5        51    9.25   114262
3          9253   3193     5        24    9.17   673572
4          9969    526     5        51    9.16   151266
...         ...    ...   ...       ...     ...      ...
12289      9316   2865     3         1    4.15      211
12290      5543   2865     3         1    4.28      183
12291      5621   2865     3         4    4.88      219
12292      6133   2865     3         1    4.98      175
12293     26081   2865     0         1    5.46      142

[11830 rows x 6 columns]

In [14]:
cat_col_names = df_clean.select_dtypes(include=['object', 'category']).columns.tolist()
print(cat_col_names)

[]

In [15]:
x = df_clean.drop(['anime_id'], axis=1)

In [32]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

def recommend_anime_by_id(target_anime_id, df_clean, x, threshold=0.8):
    # Check if the target anime ID exists in the dataframe
    if target_anime_id not in df_clean['anime_id'].values:
        raise ValueError(f"Anime ID {target_anime_id} not found in the dataset.")

    # Get the index of the target anime
    target_index = df_clean.index[df_clean['anime_id'] == target_anime_id][0]

    # Calculate cosine similarity
    similarity_matrix = cosine_similarity(x)
    similarity_scores = similarity_matrix[target_index]

    # Find indices of similar anime based on the threshold
    similar_indices = [i for i, score in enumerate(similarity_scores) if score > threshold and i != target_index]
    similar_indices = sorted(similar_indices, key=lambda i: similarity_scores[i], reverse=True)

    # Get anime IDs of the recommended anime using iloc
    recommended_anime_ids = df_clean.iloc[similar_indices]['anime_id'].values

    return recommended_anime_ids, similarity_scores[target_index]

In [33]:
target_anime_id = int(input("Enter the target anime ID: "))
threshold = float(input("Enter the similarity threshold (e.g., 0.8): "))
try:
    recommended_anime_ids, target_similarity_scores = recommend_anime_by_id(target_anime_id, df_clean, x, threshold)
    if recommended_anime_ids.size > 0:
        print(f"Recommendations for anime_id {target_anime_id}:")
        print(recommended_anime_ids)
    else:
        print(f"No similar anime found above the threshold of {threshold}.")
except ValueError as e:
    print(e)

Enter the target anime ID: 45
Enter the similarity threshold (e.g., 0.8): 0.9
Recommendations for anime_id 45:
[14837 19687  4026 ...  4657  6889   712]

In [34]:
x = df_clean.drop(['anime_id', 'members'], axis=1)
y = df_clean['anime_id']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [36]:
x_test.shape,df_clean.shape

((2366, 4), (11830, 6))

In [46]:
def recommend_test(target_anime_id, df_clean, x_test, threshold=0.8):
    if target_anime_id not in df_clean['anime_id'].values:
        raise ValueError("Target anime_id not found in the dataset.")

    target_index_in_clean = df_clean.index[df_clean['anime_id'] == target_anime_id].tolist()[0]

    if target_index_in_clean not in x_test.index:
        raise ValueError(f"Target anime_id index {target_index_in_clean} is not present in the test set.")

    target_test_index = x_test.index.get_loc(target_index_in_clean)

    # Calculate cosine similarity matrix (for the feature matrix x_test)
    similarity_matrix = cosine_similarity(x_test)
    similarity_scores = similarity_matrix[target_test_index]

    # Find indices of similar anime based on the threshold
    similar_indices = [i for i, score in enumerate(similarity_scores) if score > threshold and i != target_test_index]
    similar_indices = sorted(similar_indices, key=lambda i: similarity_scores[i], reverse=True)

    # Return recommended anime ids based on sorted similarity scores
    recommended_anime_ids = df_clean.iloc[similar_indices]['anime_id'].values
    return recommended_anime_ids, similarity_scores[target_test_index]

In [47]:
def evaluate_recommendation_system(df_clean, x_test, y_test, threshold=0.8):
    true_positive_counts = []
    actual_relevant = []  # List to store actual relevant anime ids
    for anime_id in y_test[:50]:  # Test on a sample of 50 anime for simplicity
        try:
            recommended_anime_ids, _ = recommend_test(anime_id, df_clean, x_test, threshold)
            
            # For simplicity, assuming a recommendation is relevant if any recommendations are returned
            if len(recommended_anime_ids) > 0:
                true_positive_counts.append(1)
                actual_relevant.append(1)  # Here you could match against actual relevant anime_ids
            else:
                true_positive_counts.append(0)
                actual_relevant.append(0)

        except ValueError:
            continue
    
    # Precision, recall, and F1-score calculations
    precision = precision_score(actual_relevant, true_positive_counts, zero_division=0)
    recall = recall_score(actual_relevant, true_positive_counts, zero_division=0)
    f1 = f1_score(actual_relevant, true_positive_counts, zero_division=0)

    print(f"Precision: {precision:.2f}")
    print(f"Recall: {recall:.2f}")
    print(f"F1-Score: {f1:.2f}")

In [48]:
evaluate_recommendation_system(df_clean, x_test, y_test, threshold=0.8)

Precision: 1.00
Recall: 1.00
F1-Score: 1.00

In [3]:
print("Cosine similarity cannot be used to build a learning model. It only compares vector features.")
print("Here even though the data has been split, the results only include x_test and no predictions.")
print("Therefore there is no point of the precision, recall or f1 score.")

Cosine similarity cannot be used to build a learning model. It only compares vector features.
Here even though the data has been split, the results only include x_test and no predictions.
Therefore there is no point of the precision, recall or f1 score.